### ISSUE TITLE
Pytanie

### ISSUE THREAD

**Issue by tele1** [vogel/injeqt#15]
Przepraszam ze tutaj, ale do forum musialbym sobie przypomniec haslo i login.

Jako że masz jakieś doświadczenie w programowaniu komunikatorów,
a ostatnio z kolegą znalazłem fajny komunikator, 
który fajnie działa na Manjaro Linux czy Archu
https://ring.cx/en/news#join-the-ring-project-for-the-summer

ale rozwój tego komunikatora idzie strasznie wolno.
i mam pytanie, czy słyszałeś o takim komunikatorze i czy byłbys wstanie im odrobinę pomóc ?

Dlaczego ?
- świetna jakość głosu
- świetna jakość obrazu z pulpitu.

Co z nim nie tak ?
- wersja która w Archu, Manjaro jest stara.
- kontakty się nie zapisują
- multi rozmowy są możliwe, ale generalnie nie zawsze to działa,
 oraz nie każdy wie że dany kontakt trzeba przesunąć żeby dołączyć kogoś do rozmowy grupowej
- brak ikonek
- linki nie otwierają się w przeglądarce
- a ostatnio nawet ten "Ring" się nie kompilował, bo gosc robił pod Windowsa i dopiero teraz to poprawiają.
- działa z wyłączoną zaporą sieciową, 
lub gdy dana osoba posiada router z włączonym UPnP.
Zgaduje że trzeba ustawić porty na zaporze, ale mogę się mylić, próby kolegi okazały się fiaskiem bo porty losowo są używane przy dzwonieniu i nie potrafimy tego ogarnąć a ja aktualnie nie miałem czasu jeszcze pobawić się dłużej Wireshark-iem.

**Comment by vogel** [comment]
Nie mam czasu na swoje projekty, co dopiero na cudze...
