### ISSUE TITLE
CMake Error: Unknown CMake command "qt5_use_modules"

### ISSUE THREAD

**Issue by EGD** [vogel/injeqt#23]
Build with Qt 5.11 broken, please replace `qt5_use_modules` to fix it.

**Comment by vogel** [comment]
Hi.

Are you actively using this project? If so, I'll make an update for Qt 5.11.

**Comment by EGD** [comment]
Hi.
This change needed to fix package build for openSUSE.

**Comment by vogel** [comment]
Thanks for the info. In that case it is not worth fixing, as the only one project using injeqt was Kadu, which is no longer maintained. It is better to just drop both packages.

**Comment by EGD** [comment]
Ok, thanks. I create request to drop this package.
