### ISSUE TITLE
FTBFS on Debian and forks

### ISSUE THREAD

**Issue by mati75** [vogel/injeqt#9]
Hej!

Zacząłem pakietowanie kadu 2.0 dla Debiana jak i pochodnych, czyli trzeba zacząć od budowania zależności dla tej wersji i na starcie jest problem z injeqt. Kompilacja na maszynach nie 64 bitowych kończy się tak:

https://launchpadlibrarian.net/196824107/buildlog_ubuntu-vivid-i386.injeqt_1.0.0-1_FAILEDTOBUILD.txt.gz

W tym momencie widzę, że kompiluje się poprawnie tylko na amd64, arm64, ppc64 i kfreebsd-amd64. Na pozostałych maszynach jest błąd jak wyżej dla i386.

Ze zwględu na brak czasu nie wymyśliłem jeszcze patcha na to, tak więc najpierw zgłaszam błąd.

**Comment by vogel** [comment]
Kompiluj z -DDISABLE_EXAMPLES
Wymyślę właściwą poprawkę przy okazji 1.1

**Comment by tele1** [comment]
Mam podobne bledy pod PCLinuxOS 32 bit przy kompilacji recznej.
Czyli przy 43% 
"  undefined reference to `bool QTest::qCompare<unsigned int, unsigned long>(unsigned int const&, unsigned long const&, char const*, char const*, char const*, int)' "

 cmake -DDISABLE_EXAMPLES =ON  nic nie daje
ale daje jak dam:
 cmake -DDISABLE_TESTS=ON ..
to juz bledow nie mam

log z kompilacji:
http://wklejto.pl/223035

**Comment by vogel** [comment]
Święta racja, złą flagę wkleiłem.  Oczywiście chodzi o -DDISABLE_TESTS=ON

**Comment by tele1** [comment]
Ale zes szybko odpisal :D 
Przypadkowo weszles ? Czy masz jakis alert wlaczony ?

**Comment by vogel** [comment]
Akurat jestem na kompie i pocztę sprawdzałem :)

**Comment by vogel** [comment]
Fixed: 6eb41dc52a0ee71c019a29236d6b61db1f21aa4c
